### ISSUE TITLE
22.04 /usr/share/gufw/gufw/gufw.py - missing

### ISSUE THREAD

**Issue by 0pLuS0** [costales/gufw#45]
Hello,

I'm trying to build 22.04 on Slackware 15.0

Just using ```python3 setup.py install --prefix=/usr --root=$PKG``` in a build script, when I try to run gufw, I get back at the term;

 >gufw
python3: can't open file '/usr/share/gufw/gufw/gufw.py': [Errno 2] No such file or directory

With 21.04.0 I have this in my build script;

Point gufw-pkexec to the correct python3 location and version.
sed -i "s|lib/python3.5|lib$LIBDIRSUFFIX/python3.7|g" bin/gufw-pkexec
sed 's|/usr/share/gufw/gufw/gufw.py $1|/usr/lib64/python'"${PYTHONVERSION}"'/site-packages/gufw/gufw.py "$@"|' -i bin/gufw-pkexec

But it doesn't seem to be working now with the latest gufw, I hope you can please fix this build issue.

THANKS

**Comment by 0pLuS0** [comment]
If I also try to build gufw-21.04.0 with the sed options listed above, when I run it from the term I get this back;

 ~ >gufw
python3: can't open file '/usr/lib64/python3.7/site-packages/gufw/gufw.py': [Errno 2] No such file or directory

I used before 21.04.0 in Slackware 14.2 but it doesn't compile properly either.

BUT, I want to use the latest version.

THANKS

**Comment by 0pLuS0** [comment]
Well, after posting this issue, I did added in a sed line in my slackbuild script and gufw is running.

I'm attaching the build script I used to compile 22.04.0.

Please tell me if Line 54  in this build script for the sed is ok?

THANKS

[gufw.SlackBuild.txt](https://github.com/costales/gufw/files/8250269/gufw.SlackBuild.txt)

**Comment by 0pLuS0** [comment]
Hi @costales

Do you think it possible in the future you can port this to either QT or GTK?

I love the app, I just hate the extra added needed for more deps, with webkitgtk...

Thanks for your time!

**Comment by costales** [comment]
Hi,

But it is already GTK :O

Best regards.

**Comment by 0pLuS0** [comment]
Only GTK, there is no need for Webkit2gtk, or python-distutils-extra?

I used this slackware build script as a guide, and according to it, gufw needs webkit2gtk;

https://slackbuilds.org/repository/15.0/network/gui-ufw/

Thanks

**Comment by 0pLuS0** [comment]
Hi @costales 

I'm still not sure what you mean it is already GTK, gufw is not 100% a GTK only app, by my understanding.

Slackware and Arch both list webkit2gtk as a requirement to build.

Slackware
https://slackbuilds.org/repository/15.0/network/gui-ufw/

Arch
https://archlinux.org/packages/community/any/gufw/

In simple words, my understanding is that while webkit2gtk is used to render UI, I've seen other projects use this for creating the UI, I don't understand why this has to be requirement to build gufw?

https://webkitgtk.org/

I hope in the future you can remove the requirement for this, so it's 100% only GTK.

If gufw can be built without  webkit2gtk, I would greatly appreciate it, if you would please reply to let me know?

THANKS

**Comment by costales** [comment]
Hi,
I don't remember the needs of this library. I will check ot, but I will not
have time soon.
Thank you for the feedback!
Best regards!

**Comment by 0pLuS0** [comment]
HI @costales 

I just removed webkit2gtk and tried to run gfufw, but it fails to run now without it;

```
~ pts/0 rog ~ >gufw
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/gufw/gufw.py", line 21, in <module>
    from gufw.view.gufw  import Gufw
  File "/usr/lib64/python3.9/site-packages/gufw/gufw/view/gufw.py", line 21, in <module>
    gi.require_version('WebKit2', '4.0')
  File "/usr/lib64/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit2 not available
```

It would be really great if you can code gufw to not need webkit2gtk, as it needs 5 more additional dependencies to compile it.

THANKS

**Comment by costales** [comment]
Hi,

What is happening if you remove this line:
"gi.require_version('WebKit2', '4.0')" in the file
"/usr/lib64/python3.9/site-packages/gufw/gufw/view/gufw.py", line 21

Thanks in advance!

**Comment by 0pLuS0** [comment]
Ok the UI came up, but now it shows this message;
```
~ pts/1 foo ~ >gufw
/usr/lib64/python3.9/site-packages/gufw/gufw/view/gufw.py:21: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, WebKit2
```

**Comment by costales** [comment]
Hi,

Please, try then to change:

``` 
gi.repository import Gtk, Gdk, WebKit2
```

for:

```
import gi
gi.require_version('WebKit2', '4.0')
gi.repository import Gtk, Gdk, WebKit2
```

**Comment by 0pLuS0** [comment]
Hello,

I'm confused, I don't know what you are asking me to change?

You want this section to look like this now, remove ```from``` at the last line?


import gi
gi.require_version('Gtk', '3.0')
gi.require_version('Gdk', '3.0')
gi.require_version('WebKit2', '4.0')
gi.repository import Gtk, Gdk, WebKit2

**Comment by 0pLuS0** [comment]
If I make it look like this, if I understand correctly;

import gi
gi.require_version('Gtk', '3.0')
gi.require_version('Gdk', '3.0')
gi.require_version('WebKit2', '4.0')
gi.repository import Gtk, Gdk, WebKit2

I get this at the terminal, it doesn't run;

 ~ >gufw
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/gufw/gufw.py", line 21, in <module>
    from gufw.view.gufw  import Gufw
  File "/usr/lib64/python3.9/site-packages/gufw/gufw/view/gufw.py", line 22
    gi.repository import Gtk, Gdk, WebKit2
                  ^
SyntaxError: invalid syntax

**Comment by costales** [comment]
Hi,

I think you are not working with the last commits?

I don't find any `gi.repository import Gtk, Gdk, WebKit2`.

Best regards.

**Comment by 0pLuS0** [comment]
What do you mean Tutorial, on the Home button, that tutorial section?

I thought webkit was needed for the entire UI?

Can you please consider getting rid of this webkit dependency and having this work with just GTK?

THANKS

**Comment by costales** [comment]
Hi, yes that tutorial in 1st screen. If someone can develop it, it is
welcome! Best regards

**Comment by 0pLuS0** [comment]
Hi,

Are you the developer of gufw? 

I assumed you created the Tutorial UI with webkit2?

THANKS

**Comment by 0pLuS0** [comment]
You're the developer, or you don't have the time to do this?

THANKS

**Comment by costales** [comment]
Hello, I'm sorry, but I don't work on demand. All the software I developed I developed for myself, but as a believer in free software, I released it under a free license. 
The main tutorial is a key feature and I want it. Anyway, I don't have the time or knowledge for migrating from webkit to GTK.
A hug.

**Comment by 0pLuS0** [comment]
Ok, if things might change in the future to change this, I'm sure a lot of the Linux community out there will also greatly appreciate this, because this takes 5 additional dependencies to compile, for webkit.

If it were GTK only, it wouldn't need all these extra dependencies to compile.

Don't we all hate bloat? LOL  :)

THANKS

**Comment by udpcachefix** [comment]
Weird. Why did I still receive the bug/error then? Thus I looked it up and commented here.. anyways, disregard it then.

Cheers
